services:
  web:
    build: .
    command: bash -c "rm -f /rails_app/tmp/pids/server.pid && bundle exec rails s -p ${PORT:-3000} -b '0.0.0.0'"
    volumes:
      - .:/rails_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
  
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    env_file:
      - .env
    ports:
      - "5433:5432"

volumes:
  postgres_data: